### ISSUE TITLE
Trip CRUD

### ISSUE THREAD

**Issue by Diogo-Ferreira** [Diogo-Ferreira/spring-project#4]
- Page to create / alter a trip
- Page to add a picture to a trip

**Comment by Diogo-Ferreira** [comment]
This can help : https://github.com/Zianwar/springboot-crud-demo

**Comment by LumenH** [comment]
Le template pour trip/{id} est inspiré de ceci : https://github.com/Zianwar/springboot-crud-demo/blob/master/src/main/resources/templates/productshow.html#L19

Seulement, le `th:text="${trip.id}"` ne marche absolument pas.
Notre projet semble assez ressemblant à celui du lien ci-dessus, donc je ne sais pas vraiment où ça foire.
Est-ce que c'est de nouveau un problème avec tyhmeleaf, ou alors c'est un problème au niveau du controller ? Ou du model ?

**Comment by LumenH** [comment]
En ce qui concerne l'erreur qui restait, elle était due au fait que le constructeur sans argument de Trip est un constructeur complètement vide. Pour le coup, j'ai supprimé (commenté) tous les constructeurs de Trip afin d'avoir à nouveau accès au constructeur par défaut de cette classe, comme cela est fait dans cet exemple : https://github.com/Zianwar/springboot-crud-demo/blob/master/src/main/java/com/ensat/entities/Product.java
Donc, les deux autres constructeurs qui avaient été spécifiés dans la classe, sont commentés. Ils ne semblent pas être utilisés pour l'instant, donc tout va bien. Mais le jour où il faudra les utiliser, il faudra les décommenter et faire un meilleur constructeur sans argument pour cette classe.  😊 

Sinon, mise à part pour l'ajout d'images, tâche qui revient à @SylvainRamseyer , je pense que cette issue est complète. Qu'en pensez-vous ? 😋

**Comment by Diogo-Ferreira** [comment]
@LumenH il manque juste l'ajout de l'user dans le trip à la creation, mais mise à part ça je pense que c'est bon.

**Comment by LumenH** [comment]
@Diogo-Ferreira Il faudrait aussi se débrouiller pour pouvoir ajouter les dates lors de la création du Trip. Il suffit juste de compléter le formulaire d'ajout d'un trip. Et éventuellement l'affichage d'un trip, s'il y a besoin d'afficher plus d'information que ce qu'il y a pour l'instant. 😊 
Donc je vous laisse vous charger de ça ? #QualitéLogiciel

**Comment by Diogo-Ferreira** [comment]
Oui
